#
# Ahoy configuration file.
# http://www.ahoycli.com/
#
# Provides development experience shortcuts.
---
ahoyapi: v2

commands:

  build:
    usage: Build or rebuild the project.
    cmd: ./.devtools/build.sh

  lint:
    usage: Lint code.
    cmd: ./.devtools/lint.sh

  test:
    usage: Run all tests.
    cmd: ./.devtools/test.sh
